[tool.poetry]
name = "dio-bank"
version = "0.1.0"
description = ""
authors = ["viniciusfariac <vinicius.cerqueira@sptech.school>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "*"
flask-sqlalchemy = "*"
flask-jwt-extended = "*"
flask-migrate = "^4.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
